spring:
  application:
    name: Platform Service Provider
  profiles:
    active: @profileActive@

  rabbitmq:
    host: 192.168.3.142
    port: 5672
    username: admin
    password: admin
    virtualHost: /

server:
  port: 8081


